# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "matt"
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4058", "--cpus", "4"]
  end

  config.vm.hostname = 'int-reporting-1'
  config.vm.synced_folder "~/projects/puppet", "/etc/puppet"
  config.vm.provision :shell do |shell|
      shell.path = "test.sh"
  end 
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "~/projects/puppet/manifests"
    puppet.manifest_file = "reporting.pp"
    puppet.options = "--verbose --debug"
  end
end
